---

- name: "Playbook: Install Redis"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role: # Install Redis
        name: alex.redis.install
